### ISSUE TITLE
Consfusing wording in chapter 4

### ISSUE THREAD

**Issue by Mattuuuuh** [EisenIn/Algebre-Lineaire-2#30]
Hi.

In chapter 4, between example 4.1 and lemma 4.1 you state: 

> Let us first solve the system as follows x(t)=exp(λt)v [...].

I am confused here since you set x(t) and try to solve for x(t)?
Or do you simply plug in the x(t) in the equation (4.1)? 
If so, where is the matrix A in the resulting equation?

> λ exp(λt)v = exp(λt)v

**Comment by EisenIn** [comment]
Yes, this was confusing. I hope its clear now.
